name: "Setup JDK and Gradle"
description: "Sets up JDK and Gradle with validation and caching."

inputs:
  java-version:
    description: "Java version to use. Default is 17."
    default: "17"

runs:
  using: "composite"
  steps:
    # 최신 버전의 JDK 설정
    - name: Set Up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v4.4.0
      with:
        distribution: temurin
        java-version: ${{ inputs.java-version }}

    # Gradle 래퍼 유효성 검사 및 캐시 정리 포함한 Gradle 설정
    - name: Setup Gradle with Wrapper Validation and Cache Cleanup
      uses: gradle/actions/setup-gradle@v3
      with:
        validate-wrappers: true
        gradle-home-cache-cleanup: true

    # CI용 Gradle 속성 설정
    - name: Configure CI Gradle Properties
      shell: bash 
      run: |
        mkdir -p ~/.gradle
        cp .github/ci-gradle.properties ~/.gradle/gradle.properties
