name: "CD - Create Single Milestone with Due Date Setting"

on:
  workflow_dispatch:
    inputs:
      milestone_title:
        description: "Milestone title - No spaces and no empty strings allowed"
        required: true
      due_in_days:
        description: "Due days (e.g., 7) - Only numbers allowed, no spaces and no empty strings"
        required: true

permissions: {}  # 기본 권한 제거

jobs:
  create-single-milestone:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # 마일스톤 생성 권한

    steps:
      # 마일스톤 제목 및 기한 유효성 검사
      - name: Validate Milestone Title and Due Days
        run: |
          title="${{ github.event.inputs.milestone_title }}"
          due_in_days="${{ github.event.inputs.due_in_days }}"
          if [[ -z "$title" || "$title" =~ \  ]]; then
            echo "Error: The milestone title cannot contain spaces or be an empty string."
            exit 1
          fi
          if [[ -z "$due_in_days" || "$due_in_days" =~ \  || ! "$due_in_days" =~ ^[0-9]+$ ]]; then
            echo "Error: Due days must be a number and cannot contain spaces or be an empty string."
            exit 1
          fi

      # jq 설치 여부 확인
      - name: Check if jq is Installed
        run: |
          if ! command -v jq &> /dev/null; then
            echo "Installing jq for JSON parsing..."
            sudo apt-get update && sudo apt-get install -y jq
          fi

      # 기존 활성 마일스톤 확인
      - name: Check for Existing Active Milestone
        run: |
          milestones=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/milestones")
          active_milestone_count=$(echo "$milestones" | jq '[.[] | select(.state == "open")] | length')
          if [ "$active_milestone_count" -gt 0 ]; then
            echo "Warning: An active milestone already exists. Skipping creation of a new milestone."
            echo "milestone_exists=true" >> $GITHUB_ENV
          else
            echo "milestone_exists=false" >> $GITHUB_ENV
          fi

      # 마일스톤 기한 계산
      - name: Calculate Milestone Due Date
        if: env.milestone_exists == 'false'
        run: |
          due_date=$(date -d "+${{ github.event.inputs.due_in_days }} days" +'%Y-%m-%dT00:00:00Z')
          echo "due_date=$due_date" >> $GITHUB_ENV

      # 새로운 마일스톤 생성
      - name: Create New Milestone
        if: env.milestone_exists == 'false'
        run: |
          curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/milestones \
            -d @- << EOF
          {
            "title": "${{ github.event.inputs.milestone_title }}",
            "due_on": "${{ env.due_date }}"
          }
          EOF
          echo "Success: A new milestone '${{ github.event.inputs.milestone_title }}' has been created. Due date: ${{ env.due_date }}."

      # 기존 활성 마일스톤 알림
      - name: Notify Existing Active Milestone
        if: env.milestone_exists == 'true'
        run: |
          echo "Notice: An active milestone already exists. No new milestone was created."