name: "CI - Publish Unit Test Results"

on:
  workflow_run:
    workflows: ["CI - Verify Unit Test"] # Verify 워크플로 이름과 동일해야 함
    types:
      - completed

permissions: {} # 기본 권한 제거

jobs:
  publish_results:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'
    permissions:
      checks: write # 커밋 상태 업데이트
      pull-requests: write # PR에 코멘트 작성
      actions: read # 아티팩트 다운로드에 필요

    steps:
      # 테스트 결과 다운로드
      - name: Download Test Results
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: CI - Verify Unit Test
          name: test-results
          run_id: ${{ github.event.workflow_run.id }}
          path: artifacts
          if_no_artifact_found: fail

      # 이벤트 파일 다운로드
      - name: Download Event File
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: CI - Verify Unit Test
          name: event-file
          run_id: ${{ github.event.workflow_run.id }}
          path: artifacts
          if_no_artifact_found: fail

      # 다운로드된 파일의 유효성 점검 (강제 종료하지 않음)
      - name: Validate Extracted Files
        run: |
          EVENT_JSON_PATH="artifacts/event-file/event.json"
          if [ ! -f "$EVENT_JSON_PATH" ]; then
            echo "Warning: event.json not found in $EVENT_JSON_PATH"
          fi

          XML_FILES=$(find artifacts -name "*.xml")
          if [ -z "$XML_FILES" ]; then
            echo "Warning: No XML test results found in artifacts"
          fi

      # 테스트 결과를 PR에 게시 또는 커밋 상태 업데이트
      - name: Publish Unit Test Results
        if: ${{ github.event.workflow_run.pull_requests && github.event.workflow_run.pull_requests[0] }}
        uses: EnricoMi/publish-unit-test-result-action@v2.17.1
        with:
          commit: ${{ github.event.workflow_run.head_sha }} # 관련 커밋의 SHA
          event_file: artifacts/event-file/event.json # 다운로드한 이벤트 파일 경로
          event_name: ${{ github.event.workflow_run.event }} # 이벤트 이름
          files: "artifacts/**/*.xml" # 다운로드한 JUnit XML 파일 경로
          comment_mode: update # 기존 코멘트 업데이트
          fail_on: test_failures > 0 # 실패 기준 설정
          report_individual_runs: false # 테스트 결과 요약만 게시
