name: "CI - Publish Unit Test Results"

on:
  workflow_run:
    workflows: ["CI - Verify Unit Test"]
    types:
      - completed

permissions: {} # 기본 권한 제거

jobs:
  publish_results:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'
    permissions:
      checks: write # 커밋 상태 업데이트
      pull-requests: write # PR에 코멘트 작성
      actions: read # 아티팩트 다운로드에 필요

    steps:
      # 테스트 결과 다운로드
      - name: Download Test Results
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: CI - Verify Unit Test
          name: test-results
          run_id: ${{ github.event.workflow_run.id }}
          path: artifacts/test-results
          if_no_artifact_found: fail

      # 이벤트 파일 다운로드
      - name: Download Event File
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: CI - Verify Unit Test
          name: event-file
          run_id: ${{ github.event.workflow_run.id }}
          path: artifacts/event-file
          if_no_artifact_found: fail

      # 테스트 결과 유효성 점검
      - name: Validate Test Results
        run: |
          XML_FILES=$(find artifacts/test-results -name "*.xml")
          if [ -z "$XML_FILES" ]; then
            echo "Error: No XML test results found in artifacts/test-results"
            exit 1
          fi
          echo "Found test result files: $XML_FILES"
          echo "xml_files=$XML_FILES" >> $GITHUB_ENV

      # 이벤트 파일 유효성 점검
      - name: Validate Event File
        run: |
          EVENT_JSON_PATH=$(find artifacts/event-file -name "event.json")
          if [ -z "$EVENT_JSON_PATH" ]; then
            echo "Error: event.json not found in artifacts/event-file"
            exit 1
          fi
          echo "Found event.json at $EVENT_JSON_PATH"
          echo "event_json_path=$EVENT_JSON_PATH" >> $GITHUB_ENV

      # 테스트 결과를 PR에 게시 또는 커밋 상태 업데이트
      - name: Publish Unit Test Results
        if: ${{ github.event.workflow_run.pull_requests && github.event.workflow_run.pull_requests[0] }}
        uses: EnricoMi/publish-unit-test-result-action@v2.18.0
        with:
          commit: ${{ github.event.workflow_run.head_sha }} # 커밋 SHA
          event_name: ${{ github.event.workflow_run.event }} # 이벤트 이름
          files: ${{ env.xml_files }} # 테스트 결과 경로 (xml 파일)
          event_file: ${{ env.event_json_path }} # 이벤트 파일 경로
          comment_mode: changes # 테스트 결과 변경 사항이 있을 때만 코멘트 작성
          test_file_prefix: "-artifacts/test-results" # 테스트 파일 경로가 루트 기준으로 변경되지 않으면 접두사를 추가
          check_run: true # 체크 실행을 활성화
          check_run_annotations: all tests # 모든 테스트의 주석 표시
          job_summary: true # 작업 요약을 표시
          report_individual_runs: "true" # 모든 실패를 개별적으로 표시
          ignore_runs: false # 주석 생성 활성화
